before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: M00fiw93heUOhhnOhwHkcfdXaYgPAoKhQ2IneoUjQlEXZ4lE+0apNGbOFBEGNkro060SIf4jlBTWYsYKtLj63zvzZRtWilgycpJwgD0FjpzrzCHc/yX2dNm2J1VqidNcWvD19UFguqc6DRNer5/rpIkZy3iv4CW78Lm2a8TdDeld27NK4Y6VvmpxbKUwtOUSKVpgqdkqGnMoaq4p5IV/F+uBuN2U6Rw+PXQPbVgtQSpSe7etrjWCYx9hdhIC7KWvGn8t/0qapTbqDVM9fMnPdBXb139owLLqORzJdrRwLyrp1tbT4X5yKxFZuDU6v/apPiNjhOaeaLpOynGvt0SYGgFgI2+IHDGNbvVTwB4KUgBD6wi0sAwdA38yHD2kGUSAkcDM5BX98P5H0e9BenN58A+ProLFsn3cHtjElh3vgqUJj7bCvLpImQGl2BFLtqCSxOXhn4g5umj62m5iVRg/QQ0hqiYzgJkKKi6gqLvxA99m5r8WjORaT0jDm+bOzPfKZssntnV7zVb072TPsg+ZtemgRjddjZQ+rZch0RJ5Z3l0UARPXgHy1KF0dZXH+/pyWBe7hdwfkS49OXIcgEKWOqRTiWJ8UUBv09d53XKotzCK1EqOPNns70eI0kiX2uReykRO7htZGcbOgNXagmrhG1ry7Rk4c35C51Xm3cLmGfk= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
